// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX_FnYc9cDrOTu6rOFdFoqCod2nW93tQA',
    appId: '1:883745021073:web:feff2a3e595bc34ef33330',
    messagingSenderId: '883745021073',
    projectId: 'farmer-system-670ba',
    authDomain: 'farmer-system-670ba.firebaseapp.com',
    storageBucket: 'farmer-system-670ba.firebasestorage.app',
    measurementId: 'G-0BEZEY57CB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0WI0SDPj1bFAV4i77GHx5tzlNA91TAoE',
    appId: '1:883745021073:android:33dc74675a2e7cbaf33330',
    messagingSenderId: '883745021073',
    projectId: 'farmer-system-670ba',
    storageBucket: 'farmer-system-670ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvoJxnqhMmcLVOkWYULS9zd8H73S0d6rA',
    appId: '1:883745021073:ios:2fcfcc9ab8a4127ef33330',
    messagingSenderId: '883745021073',
    projectId: 'farmer-system-670ba',
    storageBucket: 'farmer-system-670ba.firebasestorage.app',
    iosBundleId: 'com.example.farmerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvoJxnqhMmcLVOkWYULS9zd8H73S0d6rA',
    appId: '1:883745021073:ios:2fcfcc9ab8a4127ef33330',
    messagingSenderId: '883745021073',
    projectId: 'farmer-system-670ba',
    storageBucket: 'farmer-system-670ba.firebasestorage.app',
    iosBundleId: 'com.example.farmerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX_FnYc9cDrOTu6rOFdFoqCod2nW93tQA',
    appId: '1:883745021073:web:f5945e95553afc8bf33330',
    messagingSenderId: '883745021073',
    projectId: 'farmer-system-670ba',
    authDomain: 'farmer-system-670ba.firebaseapp.com',
    storageBucket: 'farmer-system-670ba.firebasestorage.app',
    measurementId: 'G-3Z569X6717',
  );
}
