name: farmer_app
description: "AI Farmer Advisory System"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # API
  http: ^1.6.0

  # Voice AI
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.5

  # Images
  image_picker: ^1.2.2

  # State
  provider: ^6.1.5+1

  # Local Storage
  shared_preferences: ^2.5.5

  # Firebase
  firebase_auth: ^6.4.0
  firebase_core: ^4.5.0

  # Search Suggestions
  flutter_typeahead: ^6.0.0

  # PREMIUM UI
  glassmorphism: ^3.0.0
  google_fonts: ^6.3.0
  animate_do: ^4.2.0
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
